import { ProductI } from './interfaces/product'

export const products: ProductI[] = [
  {
    id: 1,
    imgSrc: 'src/assets/products/Expresso Tradicional.png',
    title: 'Expresso Tradicional',
    tags: ['TRADICIONAL'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
  },
  {
    id: 2,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'Expresso Americano',
    tags: ['TRADICIONAL'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 19.9,
  },
  {
    id: 3,
    imgSrc: 'src/assets/products/Expresso Cremoso.png',
    title: 'Expresso Cremoso',
    tags: ['TRADICIONAL'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 15,
  },
  {
    id: 4,
    imgSrc: 'src/assets/products/Café Gelado.png',
    title: 'Expresso Gelado',
    tags: ['TRADICIONAL', 'GELADO'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 22,
  },
  {
    id: 5,
    imgSrc: 'src/assets/products/Café com Leite.png',
    title: 'Café com Leite',
    tags: ['TRADICIONAL', 'COM LEITE'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 10,
  },
  {
    id: 6,
    imgSrc: 'src/assets/products/Latte.png',
    title: 'Latte',
    tags: ['TRADICIONAL', 'COM LEITE'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 16.9,
  },
  {
    id: 7,
    imgSrc: 'src/assets/products/Capuccino.png',
    title: 'Capuccino',
    tags: ['TRADICIONAL', 'COM LEITE'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
  },
  {
    id: 8,
    imgSrc: 'src/assets/products/Macchiato.png',
    title: 'Macchiato',
    tags: ['TRADICIONAL', 'COM LEITE'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 11.5,
  },
  {
    id: 9,
    imgSrc: 'src/assets/products/Moccacino.png',
    title: 'Mocaccino',
    tags: ['TRADICIONAL', 'COM LEITE'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 15.9,
  },
  {
    id: 10,
    imgSrc: 'src/assets/products/Chocolate Quente.png',
    title: 'Chocolate Quente',
    tags: ['ESPECIAL', 'COM LEITE'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 21.5,
  },
  {
    id: 11,
    imgSrc: 'src/assets/products/Cubano.png',
    title: 'Cubano',
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
  },
  {
    id: 12,
    imgSrc: 'src/assets/products/Havaiano.png',
    title: 'Havaiano',
    tags: ['ESPECIAL'],
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 7,
  },
  {
    id: 13,
    imgSrc: 'src/assets/products/Árabe.png',
    title: 'Árabe',
    tags: ['ESPECIAL'],
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 8.9,
  },
  {
    id: 14,
    imgSrc: 'src/assets/products/Irlandês.png',
    title: 'Irlandês',
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 22.9,
  },
]
