import { ProductI } from './interfaces/product'

export const products: ProductI[] = [
  {
    id: 1,
    imgSrc: 'src/assets/products/Expresso Tradicional.png',
    title: 'Expresso Tradicional',
    tags: ['TRADICIONAL'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
  },
  {
    id: 2,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 3,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 4,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 5,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 6,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 7,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 8,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 9,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 10,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 11,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 12,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 13,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
  {
    id: 14,
    imgSrc: 'src/assets/products/Americano.png',
    title: 'produto 2',
    tags: ['TAG'],
    description: 'descrição',
    price: 19.9,
  },
]
